# Keep your database.yml DRY.
common: &common
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: Sidd
  password:  # from psql setup, see Postgresql

test:
  <<: *common
  database: myapp_test
  
production:
  <<: *common
  database: myapp_production

development:
  <<: *common
  database: myapp_development
  host: localhost
 